[phases.setup]
nixPkgs = ["python313", "pango", "cairo", "gdk-pixbuf", "libffi", "fontconfig", "freetype"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python server.py"
